
Exception on /sample-test [GET]
Traceback (most recent call last):
  File "/Users/hiephuynh/Documents/revature/project1/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hiephuynh/Documents/revature/project1/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hiephuynh/Documents/revature/project1/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hiephuynh/Documents/revature/project1/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hiephuynh/Documents/revature/project1/website/views.py", line 19, in testing_db
    1/0
ZeroDivisionError: division by zero
